{{- if and .Values.metrics.enabled .Values.metrics.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "memreload.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "memreload.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "memreload.selectorLabels" . | nindent 4 }}
  ports:
    - name: metrics
      port: {{ .Values.metrics.service.port }}
      targetPort: metrics
{{- end }}
{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "memreload.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "memreload.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "memreload.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      interval: 30s
{{- end }}
