//go:build !ignore_autogenerated

// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerOverride) DeepCopyInto(out *ContainerOverride) {
	*out = *in
	in.Detection.DeepCopyInto(&out.Detection)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerOverride.
func (in *ContainerOverride) DeepCopy() *ContainerOverride {
	if in == nil {
		return nil
	}
	out := new(ContainerOverride)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DetectionSpec) DeepCopyInto(out *DetectionSpec) {
	*out = *in
	if in.ThresholdAbsolute != nil {
		in, out := &in.ThresholdAbsolute, &out.ThresholdAbsolute
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.Window != nil {
		in, out := &in.Window, &out.Window
		*out = new(v1.Duration)
		**out = **in
	}
	if in.TrendMinGrowth != nil {
		in, out := &in.TrendMinGrowth, &out.TrendMinGrowth
		x := (*in).DeepCopy()
		*out = &x
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DetectionSpec.
func (in *DetectionSpec) DeepCopy() *DetectionSpec {
	if in == nil {
		return nil
	}
	out := new(DetectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InFlightRollout) DeepCopyInto(out *InFlightRollout) {
	*out = *in
	in.DispatchedAt.DeepCopyInto(&out.DispatchedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InFlightRollout.
func (in *InFlightRollout) DeepCopy() *InFlightRollout {
	if in == nil {
		return nil
	}
	out := new(InFlightRollout)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintenanceWindow) DeepCopyInto(out *MaintenanceWindow) {
	*out = *in
	if in.Days != nil {
		in, out := &in.Days, &out.Days
		*out = make([]Day, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintenanceWindow.
func (in *MaintenanceWindow) DeepCopy() *MaintenanceWindow {
	if in == nil {
		return nil
	}
	out := new(MaintenanceWindow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MemoryLeakPolicy) DeepCopyInto(out *MemoryLeakPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MemoryLeakPolicy.
func (in *MemoryLeakPolicy) DeepCopy() *MemoryLeakPolicy {
	if in == nil {
		return nil
	}
	out := new(MemoryLeakPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MemoryLeakPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MemoryLeakPolicyList) DeepCopyInto(out *MemoryLeakPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MemoryLeakPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MemoryLeakPolicyList.
func (in *MemoryLeakPolicyList) DeepCopy() *MemoryLeakPolicyList {
	if in == nil {
		return nil
	}
	out := new(MemoryLeakPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MemoryLeakPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MemoryLeakPolicySpec) DeepCopyInto(out *MemoryLeakPolicySpec) {
	*out = *in
	out.WorkloadRef = in.WorkloadRef
	in.Detection.DeepCopyInto(&out.Detection)
	if in.Cooldown != nil {
		in, out := &in.Cooldown, &out.Cooldown
		*out = new(v1.Duration)
		**out = **in
	}
	if in.StartupGrace != nil {
		in, out := &in.StartupGrace, &out.StartupGrace
		*out = new(v1.Duration)
		**out = **in
	}
	if in.Containers != nil {
		in, out := &in.Containers, &out.Containers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ContainerOverrides != nil {
		in, out := &in.ContainerOverrides, &out.ContainerOverrides
		*out = make([]ContainerOverride, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ProfileCapture != nil {
		in, out := &in.ProfileCapture, &out.ProfileCapture
		*out = new(bool)
		**out = **in
	}
	if in.MaintenanceWindows != nil {
		in, out := &in.MaintenanceWindows, &out.MaintenanceWindows
		*out = make([]MaintenanceWindow, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NotifyRoutes != nil {
		in, out := &in.NotifyRoutes, &out.NotifyRoutes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MemoryLeakPolicySpec.
func (in *MemoryLeakPolicySpec) DeepCopy() *MemoryLeakPolicySpec {
	if in == nil {
		return nil
	}
	out := new(MemoryLeakPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MemoryLeakPolicyStatus) DeepCopyInto(out *MemoryLeakPolicyStatus) {
	*out = *in
	if in.LastRestartAt != nil {
		in, out := &in.LastRestartAt, &out.LastRestartAt
		*out = (*in).DeepCopy()
	}
	if in.WindowStart != nil {
		in, out := &in.WindowStart, &out.WindowStart
		*out = (*in).DeepCopy()
	}
	if in.InFlight != nil {
		in, out := &in.InFlight, &out.InFlight
		*out = new(InFlightRollout)
		(*in).DeepCopyInto(*out)
	}
	if in.NextEligibleRestart != nil {
		in, out := &in.NextEligibleRestart, &out.NextEligibleRestart
		*out = (*in).DeepCopy()
	}
	if in.LastProfile != nil {
		in, out := &in.LastProfile, &out.LastProfile
		*out = new(ProfileRef)
		(*in).DeepCopyInto(*out)
	}
	if in.LastNotification != nil {
		in, out := &in.LastNotification, &out.LastNotification
		*out = new(NotificationRef)
		(*in).DeepCopyInto(*out)
	}
	if in.History != nil {
		in, out := &in.History, &out.History
		*out = make([]RestartRecord, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MemoryLeakPolicyStatus.
func (in *MemoryLeakPolicyStatus) DeepCopy() *MemoryLeakPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(MemoryLeakPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotificationRef) DeepCopyInto(out *NotificationRef) {
	*out = *in
	in.NotifiedAt.DeepCopyInto(&out.NotifiedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotificationRef.
func (in *NotificationRef) DeepCopy() *NotificationRef {
	if in == nil {
		return nil
	}
	out := new(NotificationRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProfileRef) DeepCopyInto(out *ProfileRef) {
	*out = *in
	in.CapturedAt.DeepCopyInto(&out.CapturedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProfileRef.
func (in *ProfileRef) DeepCopy() *ProfileRef {
	if in == nil {
		return nil
	}
	out := new(ProfileRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestartRecord) DeepCopyInto(out *RestartRecord) {
	*out = *in
	in.TriggeredAt.DeepCopyInto(&out.TriggeredAt)
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestartRecord.
func (in *RestartRecord) DeepCopy() *RestartRecord {
	if in == nil {
		return nil
	}
	out := new(RestartRecord)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadRef) DeepCopyInto(out *WorkloadRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadRef.
func (in *WorkloadRef) DeepCopy() *WorkloadRef {
	if in == nil {
		return nil
	}
	out := new(WorkloadRef)
	in.DeepCopyInto(out)
	return out
}
